### ISSUE TITLE
Retrieval speed problem

### ISSUE THREAD

**Issue by zhangyanbo2007** [tuan3w/visual_search#17]
Hello, I want to ask how fast to search in this way, I have 140000 images, given a picture retrieval of the most similar 5 pictures, can be recalled in 1 second?

**Comment by tuan3w** [comment]
I think it's possible. Hamming distance is pretty fast to compute. You can also add more ES instances to reduce search time.

**Comment by zhangyanbo2007** [comment]
Thank you for your reply.I'm trying to do it with a similarity search engine like annoy or faiss. Do you know this? Isn't this going to be faster than elasticsearch?

**Comment by turpure** [comment]
I am doing the same and I am tring to reduce the reqeust time.Maybe elasticsearch cluster is a good solution. I am not suer but I will test.

**Comment by zhangyanbo2007** [comment]
> I am doing the same and I am tring to reduce the reqeust time.Maybe elasticsearch cluster is a good solution. I am not suer but I will test.

add wechat:15821444815,Talk to each other.

**Comment by tuan3w** [comment]
There are many ways to solve one problem.About searching time, I can't tell all of them but some ideas might help:
- Reduce feature length
- Add more machines to ES cluster.
-  LSH approaches (annoy,...)
- Product quantization
...
The reason you might interest in ES approach because you can custom relevant score (e.g show newest items first,...).
You can try to search about "visual search" to get overview about the current systems.
I will close this issue here.

**Comment by zhangyanbo2007** [comment]
Thank you, I am glad to hear from you, I think so, in fact I did try the annoy, the effect is good, and then you said the custom relevant score I think is also very good, I will try later.
