### ISSUE TITLE
whether support elasticseach6.8.0 version?

### ISSUE THREAD

**Issue by sunweiconfidence** [tuan3w/visual_search#20]
we want to test on elasticsearch6.8.0 , whether support it? if not, what do we need to do? thanks

**Comment by slothkong** [comment]
@sunweiconfidence did you succeed testing with the newer version of elasticsearch? As you can see in the versions is specified in the corresponding Dockerfile:
https://github.com/tuan3w/visual_search/blob/62665d4ac58669bad8e7f5ffed18d2914ffa8b01/elasticsearch/Dockerfile#L1

If you want to update Im afraid you will have to make changed to the elasticsearch plug-in, as @tuan3w points out:
https://github.com/tuan3w/visual_search/blob/62665d4ac58669bad8e7f5ffed18d2914ffa8b01/elasticsearch/es-plugin/plugin-descriptor.properties#L65-L70

I had previously had to update the java compiling version in order to run in a more modern version of elasticsearch, like shown in commit https://github.com/tuan3w/visual_search/pull/19/commits/5d17feaed80dc9d1634dade82a82a1aa5164bb79. Changes are you will need to do something similar and recompile the plugin using [maven](https://maven.apache.org/plugins/maven-compiler-plugin/).
